### ISSUE TITLE
Misleading error message on missing plugin

### ISSUE THREAD

**Issue by Preeticp** [projectatomic/adb-atomic-developer-bundle#245] opened 2016-02-19 11:18 UTC
```
[pchandra@pchandra adb-test]$ vagrant box outdated
There was an error loading a Vagrantfile. The file being loaded
and the error message are shown below. This is usually caused by
a syntax error.

Path: /home/pchandra/Vagrant/adb-test/Vagrantfile
Line number: 8
Message: RuntimeError: vagrant-service-manager plugin is not installed, run `vagrant plugin install vagrant-service-manager` to install the plugin.
```

It looks like the file has a syntax error and not that something is missing on my computer.

**Comment by brgnepal** [comment] 2016-02-23 12:43
@Preeticp : It is not a syntax error. 
To make it work, you need to first install plugin `vagrant-service-manager`.

**Comment by Preeticp** [comment] 2016-02-23 15:27
Exactly @budhrg, so the error message is misleading. Especially the first part of the message, which reads ' There was an error loading a Vagrantfile. The file being loaded and the error message are shown below. This is usually caused by a syntax error.' 
So it implies that the file has a syntax error and not that the vagrant-service-manager plugin is missing on my computer.

**Comment by hferentschik** [comment] 2016-03-24 09:58
This is really a duplicate of https://github.com/projectatomic/adb-atomic-developer-bundle/issues/256

**Comment by praveenkumar** [comment] 2016-04-04 08:14
I am going to close this issue because this is already in discussion #256

**Closed as completed by praveenkumar** 2016-04-04 08:14 UTC
