### ISSUE TITLE
Openshift Vagrant fails while provisioning

### ISSUE THREAD

**Issue by surajssd** [projectatomic/adb-atomic-developer-bundle#233] opened 2016-02-13 07:11 UTC
[Openshift Vagrant](https://github.com/projectatomic/adb-atomic-developer-bundle/blob/master/components/centos/centos-openshift-setup/Vagrantfile) fails while provisioning as below.

Steps to re-create:

``` bash

[vagrant@centos7-adb ~]$ exit
logout
Connection to 192.168.121.201 closed.

 [hummer@dhcp35-17 openshift] $ vagrant halt
==> default: Halting domain...
[hummer@dhcp35-17 openshift] $ vagrant up
Bringing machine 'default' up with 'libvirt' provider...
==> default: Starting domain.
==> default: Waiting for domain to get an IP address...
==> default: Waiting for SSH to become available...
==> default: Creating shared folders metadata...
==> default: Rsyncing folder: /home/hummer/atomic/openshift/ => /vagrant
==> default: Machine already provisioned. Run `vagrant provision` or use the `--provision`
==> default: flag to force provisioning. Provisioners marked to run always will still run.

[hummer@dhcp35-17 openshift] $ vagrant provision
==> default: Running provisioner: shell...
   default: Running: inline script
==> default: Running provisioner: shell...
   default: Running: inline script
==> default: [INFO] Pull the openshift/origin:v1.1.1 Docker image ...
==> default: Trying to pull repository docker.io/openshift/origin ...
==> default: v1.1.1: Pulling from openshift/origin
==> default: 47d44cb6f252: Already exists
==> default: 838c1c5c4f83: Already exists
==> default: 5764f0a31317: Already exists
==> default: 60e65a8e4030: Already exists
==> default: befc3e448942: Already exists
==> default: 2d5ac43b36d9: Already exists
==> default: 359237930c6a: Already exists
==> default: bb1a73504ce1: Already exists
==> default: 1a58e5b7094e: Already exists
==> default: 156c203ea96d: Already exists
==> default: 36761a9b44e9: Already exists
==> default: e601643d77c2: Already exists
==> default: 247f5a5a0b09: Already exists
==> default: f09fd95e9c8e: Already exists
==> default: 046b182a952b: Already exists
==> default: Digest: sha256:e7d4c7af556aeca1d6e294b3b13ba56a856e449f3a2c0cd391496445fb499743
==> default: Status: Image is up to date for docker.io/openshift/origin:v1.1.1
==> default: Error response from daemon: Conflict: Tag v1.1.1 is already set to image 046b182a952b3830492d9c4bcb8cfd417947e146d23d4f1690387ef9535b0a7e, if you want to replace it, please use -f option
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
[hummer@dhcp35-17 openshift] $
```

**Comment by LalatenduMohanty** [comment] 2016-02-17 09:54
@surajssd this seems to be a duplicate of https://github.com/projectatomic/adb-atomic-developer-bundle/issues/224.

**Comment by surajssd** [comment] 2016-02-17 11:22
So this can be marked as **Duplicate**, with the release of ADB 1.7.0 and newer `Vagrantfile` if everything goes well.

**Comment by surajssd** [comment] 2016-02-18 08:44
@LalatenduMohanty this and #234 can be closed I think.

**Closed as completed** 2016-02-18 12:43 UTC
