### ISSUE TITLE
Add capability to forward ADB box port to host machine

### ISSUE THREAD

**Issue by navidshaikh** [projectatomic/adb-atomic-developer-bundle#87] opened 2015-09-18 11:11 UTC
User story: I am an ADB user, I deployed an atomicapp application inside ADB, now I want to test out if my application is configured properly. I want a way to access the application from host machine (forwarded) port. 

This is usually the case with web applications. The user may not want to update the Vagrantfile for forwarded ports every time an app has to be tested. There should some better way to handle this. May be via some plugin ?

**Comment by LalatenduMohanty** [comment] 2015-09-30 05:36
@navidshaikh I think this is duplicate of #82 .

**Comment by bexelbie** [comment] 2015-10-13 09:21
closing as duplicate

**Closed as completed by bexelbie** 2015-10-13 09:21 UTC
Labels: enhancement
