### ISSUE TITLE
rsync: inconsistent behaviour between Vagrantfiles

### ISSUE THREAD

**Issue by optak** [projectatomic/adb-atomic-developer-bundle#437] opened 2016-06-10 11:30 UTC
rsync $PWD into /vagrant during vagrant up doesn't work for rhel-ose Vagrantfile (but works for k8s)
Reproduce on Red Hat Enterprise Linux 7 (libvirt) and Windows 7 (VirtualBox).
when running `vagrant rsync --debug`, it returns 0 but rsync into /vagrant in VM is not done.
Debug log: [vagrant-rsync.txt](https://github.com/projectatomic/adb-atomic-developer-bundle/files/308886/vagrant-rsync.txt)

**Comment by praveenkumar** [comment] 2016-06-13 05:54
@optak I am not sure why you want to do `vagrant rsync` because we are shipping now `vagrant-sshfs` and sshfs suppose to handle 2-way sync. Any specific reason?

**Comment by LalatenduMohanty** [comment] 2016-06-13 06:13
@optak this is as designed . We have disabled rsync https://github.com/projectatomic/adb-atomic-developer-bundle/blob/master/components/rhel/rhel-ose/Vagrantfile#L50 

As @praveenkumar mentioned it is disabled as we are using vagrant-sshfs now.

**Comment by LalatenduMohanty** [comment] 2016-06-13 06:17
Closing the issue. Please reopen if you do not agree with the resolution.

**Closed as completed** 2016-06-13 06:17 UTC

**Comment by optak** [comment] 2016-06-13 08:32
I 'm not telling I want this, just that it has change behaviour and I didn't know it's desired change (so creating issue for discussion).
I still think it's not correct, because sshfs is configured in both Vagrantfiles rhel-ose and rhel-k8s-singlenode-setup, but rsync is disabled only in rhel-ose.
So if it's desired to not sync with rsync, please make this change to all Vagrantfiles.

**Comment by hferentschik** [comment] 2016-06-15 08:24
The ultimate solution is to disable rsync in the default Vagrantfile of the box. This requires a change in ImageFactory (pending pull request I believe). Once this is merged all VMs won't have the /vagrant sync anymore.

For the CDK we explicitly disabled it via the _Vagrantfile_, since using the rsync synced folder creates problem on Windows. Whether we should have applied this change to all Vagrantfiles is debatable.

**Comment by optak** [comment] 2016-06-15 08:29
I don't think rsync is much problem on windows, but let say it is. So now, we have 1 Vagrantfile without rsync and 1 with rsync (suppose to have problems).

**Comment by hferentschik** [comment] 2016-06-15 08:44
> I don't think rsync is much problem on windows, but let say it is.

I know it is. I am bumped into it multiple times.
