### ISSUE TITLE
SSH login failure on `vagrant up` when used with rsync custom path

### ISSUE THREAD

**Issue by pvalena** [projectatomic/adb-atomic-developer-bundle#199] opened 2016-01-18 11:55 UTC
Waiting indefinitely on `vagrant up ; vagrant halt ; vagrant up` when used with rsync custom path.
Last output 'Waiting for SSH to become available...'.

Vagrantfile from: https://github.com/projectatomic/adb-atomic-developer-bundle/blob/master/components/centos/centos-docker-base-setup/Vagrantfile

Added rsync synced_folder configuration.

Steps to reproduce:

$ cat Vagrantfile | grep rsync
  config.vm.synced_folder ".", "/home/vagrant", type: "rsync"

$ vagrant up
Bringing machine 'default' up with 'libvirt' provider...
==> default: Creating image (snapshot of base box volume).
    .   .   .
==> default: Waiting for SSH to become available...
    default:
    default: Vagrant insecure key detected. Vagrant will automatically replace
    default: this with a newly generated keypair for better security.
    default:
    default: Inserting generated public key within guest...
    default: Removing insecure key from the guest if it's present...
    default: Key inserted! Disconnecting and reconnecting using new SSH key...
==> default: Configuring and enabling network interfaces...
==> default: Rsyncing folder: /home/brq/pvalena/Work/RH/adb/docker-base-setup/ => /home/vagrant

$ vagrant halt
==> default: Halting domain...

$ vagrant up
Bringing machine 'default' up with 'libvirt' provider...
==> default: Starting domain.
==> default: Waiting for domain to get an IP address...
==> default: Waiting for SSH to become available...

**Comment by praveenkumar** [comment] 2016-01-18 12:11
@pvalena Can you please try it again because I am not able to reproduce this issue (tried twice with steps).

```
$ vagrant up 
Bringing machine 'default' up with 'libvirt' provider...
==> default: Creating image (snapshot of base box volume).
==> default: Creating domain with the following settings...
==> default:  -- Name:              base_centos_default
...
==> default: Creating shared folders metadata...
==> default: Starting domain.
==> default: Waiting for domain to get an IP address...
==> default: Waiting for SSH to become available...
    default: 
    default: Vagrant insecure key detected. Vagrant will automatically replace
    default: this with a newly generated keypair for better security.
    default: 
    default: Inserting generated public key within guest...
    default: Removing insecure key from the guest if it's present...
    default: Key inserted! Disconnecting and reconnecting using new SSH key...
==> default: Configuring and enabling network interfaces...
==> default: Rsyncing folder: /home/prkumar/work/vagrant/base_centos/ => /vagrant
==> default: Rsyncing folder: /home/prkumar/work/vagrant/base_centos/ => /home/prkumar/Public

$ vagrant halt
==> default: Halting domain...

$ vagrant up
Bringing machine 'default' up with 'libvirt' provider...
==> default: Starting domain.
==> default: Waiting for domain to get an IP address...
==> default: Waiting for SSH to become available...
==> default: Creating shared folders metadata...
==> default: Rsyncing folder: /home/prkumar/work/vagrant/base_centos/ => /vagrant
==> default: Rsyncing folder: /home/prkumar/work/vagrant/base_centos/ => /home/prkumar/Public
==> default: Machine already provisioned. Run `vagrant provision` or use the `--provision`
==> default: flag to force provisioning. Provisioners marked to run always will still run.

$ vagrant halt
==> default: Halting domain...

$ vagrant up
Bringing machine 'default' up with 'libvirt' provider...
==> default: Starting domain.
==> default: Waiting for domain to get an IP address...
==> default: Waiting for SSH to become available...
==> default: Creating shared folders metadata...
==> default: Rsyncing folder: /home/prkumar/work/vagrant/base_centos/ => /vagrant
==> default: Rsyncing folder: /home/prkumar/work/vagrant/base_centos/ => /home/prkumar/Public
==> default: Machine already provisioned. Run `vagrant provision` or use the `--provision`
==> default: flag to force provisioning. Provisioners marked to run always will still run.
```

**Comment by pvalena** [comment] 2016-01-18 12:43
You are correct, different path works ok.
The issue is with path '/home/vagrant' (on the guest machine) specifically. Is this path reserved for something else? 
Thank you for help.

**Comment by pvalena** [comment] 2016-01-18 12:48
Additionally, here is my vagrant version: 1.7.4-2.fc23 (I am on Fedora 23.)

And current plugin versions:

$ vagrant plugin list  
vagrant-adbinfo (0.0.9)
vagrant-libvirt (0.0.32, system)
vagrant-registration (1.1.0)
- Version Constraint: 1.1.0

Issue occured without -adbinfo and -registration plugins too. And with older version (0.0.30) of vagrant-libvirt also.

**Comment by praveenkumar** [comment] 2016-01-19 05:47
@pvalena I did a debug today on this issue with `/home/vagrant/` and able to reproduce it, took me quite a time to understand whats going on underneath. 

When you rsync `/home/vagrant` then it will overwrite home directory of vagrant box because it also have vagrant as user (by default) so ssh keys are also overwritten and there will no keys which it can validate against.

```
==> default: Configuring and enabling network interfaces...
==> default: Rsyncing folder: /home/prkumar/work/vagrant/base_centos/ => /vagrant
```

==> default: Rsyncing folder: /home/prkumar/work/vagrant/base_centos/ => /home/vagrant :boom: (overwrite home directory)

So don't use `/home/vagrant` for rsync otherwise this will occur for sure. Hope this helps, will close this bug once I have your confirmation about this issue.

**Comment by pvalena** [comment] 2016-01-25 15:55
Yes, there is no issue rsyncing another directory. Thank you.

**Comment by praveenkumar** [comment] 2016-01-25 17:53
Thanks @pvalena for confirmation. Closing this issue.

**Closed as completed by praveenkumar** 2016-01-25 17:53 UTC
Labels: bug
