### ISSUE TITLE
Docker daemon returns header text/plain instead of application/json

### ISSUE THREAD

**Issue by mmalina** [projectatomic/adb-atomic-developer-bundle#511] opened 2016-08-17 08:56 UTC
Docker connection in Eclipse to stopped working in cdk 2.2 rc1 (it works fine with cdk 2.1). The reason is that the spotify docker client expects a header of application/json in the json response, but the docker daemon now returns text/plain . At least at first sight it looks like a bug.

See the JBIDE issue for more details: https://issues.jboss.org/browse/JBIDE-23009

**Comment by praveenkumar** [comment] 2016-08-17 10:42
@budhrg please have a look into this.

**Comment by praveenkumar** [comment] 2016-08-19 12:17
@mmalina This is docker issue for sure. I tested with docker-1.9 and everything went well even all the latest plugins and then I updated to docker-1.10.3 and not able to connect to eclipse in CDK. In ADB everything is working as expected even docker version is same.

In ADB

```
[vagrant@adb ~]$ docker -v
Docker version 1.10.3, build d381c64-unsupported
[vagrant@adb ~]$ rpm -qa docker
docker-1.10.3-46.el7.centos.10.x86_64
```

In CDK

```
[root@rhel-cdk vagrant]# docker -v
Docker version 1.10.3, build 2a93377-unsupported
[root@rhel-cdk vagrant]# rpm -qa docker
docker-1.10.3-46.el7.10.x86_64
```

CC @rhatdan

**Comment by brgnepal** [comment] 2016-08-19 12:21
@mmalina To add more here, note that the docker version is same in both ADB and CDK cases, i.e `1.10.3` but the build commit is different .

**Comment by mmalina** [comment] 2016-08-19 12:28
@praveenkumar , docker -v is the version of docker client. I think docker daemon API version is critical here.
For example I have cli docker client version 1.10.3 on my machine. And when I run docker-machine, I get this:
Error response from daemon: client is newer than server (client API version: 1.22, server API version: 1.21)
But Eclipse connects to this daemon without a problem - so API version 1.21 is fine in Eclipse.

When I start CDK 2.2 rc1 and then setup my cli docker client, I get this:
$ docker version 
Client:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.6
 Git commit:   d12ea79c9de6d144ce6bc7ccfe41c507cca6fd35
 Built:  
 OS/Arch:      darwin/amd64

Server:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.6.2
 Git commit:   2a93377-unsupported
 Built:        Fri Jul 29 13:45:25 2016
 OS/Arch:      linux/amd64

So it seems the unwanted change was brought it API version 1.22?
I will see if there is a new docker toolbox available which also uses 1.22 and if that breaks Eclipse also.

**Comment by mmalina** [comment] 2016-08-19 12:35
So I installed the latest Docker Toolbox - docker daemon API version is even newer 1.24. And it works fine in Eclipse. Not sure what to make of it...

$ docker version
Client:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.6
 Git commit:   d12ea79c9de6d144ce6bc7ccfe41c507cca6fd35
 Built:  
 OS/Arch:      darwin/amd64

Server:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 23:54:00 2016
 OS/Arch:      linux/amd64

**Comment by mmalina** [comment] 2016-08-19 12:44
Looking at the API reference doc, even in version 1.22 the header should indeed still be application/json:
https://github.com/docker/docker/blob/master/docs/reference/api/docker_remote_api_v1.22.md#21-containers

So now we need to track down where this is broken - do we have our own fork of docker where this could be tracked down?

**Comment by rhatdan** [comment] 2016-08-19 12:59
@runcom PTAL
What call is returning plain text and not json?

**Comment by mmalina** [comment] 2016-08-19 13:05
@rhatdan I am not sure, this is from the JIRA:

> Docker daemon in CDK 2.2 returns a response that contains the list of containers in a JSON format, but the 'content' header is text/plain instead of application/json and thus, the Docker client does not know how to handle/deserialize the response message.

@xcoulon can you find the exact request?

**Comment by runcom** [comment] 2016-08-19 15:01
I'll take a look at this shortly, should be something with some of our patches probably (or some backport to be done since I remember a similar issue upstream)

**Comment by xcoulon** [comment] 2016-08-19 15:20
@rhatdan @mmalina this is in the response to the request to obtain the list of containers, i.e. : 
`GET ${DOCKER_HOST}/containers/json?all=1`

**Comment by xcoulon** [comment] 2016-08-19 15:46
As a matter of example, here's the raw response I got when requesting on the endpoint mentioned above:

> curl --cacert $DOCKER_CERT_PATH/ca.pem --cert $DOCKER_CERT_PATH/cert.pfx --pass supersecret -v https://172.28.128.3:2376/containers/json
> -   Trying 172.28.128.3...
> - Connected to 172.28.128.3 (172.28.128.3) port 2376 (#0)
> - WARNING: SSL: Certificate type not set, assuming PKCS#12 format.
> - Client certificate: client
> - WARNING: using IP address, SNI is being disabled by the OS.
> - TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
> - Server certificate: example.com
> - Server certificate: example.com
>   GET /containers/json HTTP/1.1
>   Host: 172.28.128.3:2376
>   User-Agent: curl/7.43.0
>   Accept: _/_
> 
> < HTTP/1.1 200 OK
> < Date: Fri, 19 Aug 2016 15:43:12 GMT
> < Content-Type: text/plain; charset=utf-8
> < Transfer-Encoding: chunked
> <

As you can see, the `Content-Type` header is `text/plain` which is not handled by the Docker client that we use. 
This looks very much like an old issue that we had in the past: [https://github.com/docker/docker/issues/4121]() 

UPDATE: the `.pfx` file used in the command above was generated using the following command:
`openssl pkcs12 -export -in $DOCKER_CERT_PATH/cert.pem -inkey $DOCKER_CERT_PATH/key.pem -out $DOCKER_CERT_PATH/cert.pfx -password pass:supersecret`

This file was created because on MacOSX, the following command failed:
`curl -i --cacert $DOCKER_CERT_PATH/ca.pem --cert $DOCKER_CERT_PATH/cert.pem --key $DOCKER_CERT_PATH/key.pem https://172.28.128.3:2376/containers/json?all=1`

**Comment by praveenkumar** [comment] 2016-08-22 05:41
@runcom Anything you found which causing this?

**Comment by praveenkumar** [comment] 2016-08-22 10:31
@runcom @rhatdan I also created a bugzilla bug to track downstream: https://bugzilla.redhat.com/show_bug.cgi?id=1368999

**Comment by praveenkumar** [comment] 2016-08-22 11:12
Just in case if that help, I tried same with ADB (which is based on CentOS) and have `Docker version 1.10.3, build d381c64-unsupported` have given expected output to curl query but for CDK it throw `text/plain` as Content type.

```
➜  adb curl --cacert $DOCKER_CERT_PATH/ca.pem --cert $DOCKER_CERT_PATH/cert.pfx --pass supersecret -v https://172.28.128.4:2376/images/json
* Hostname was NOT found in DNS cache
*   Trying 172.28.128.4...
* Connected to 172.28.128.4 (172.28.128.4) port 2376 (#0)
* WARNING: SSL: Certificate type not set, assuming PKCS#12 format.
* Client certificate: client
* WARNING: using IP address, SNI is being disabled by the OS.
* TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA
* Server certificate: example.com
* Server certificate: example.com
> GET /images/json HTTP/1.1
> User-Agent: curl/7.37.1
> Host: 172.28.128.4:2376
> Accept: */*
>
< HTTP/1.1 200 OK
< Content-Type: application/json
* Server Docker/1.10.3 (linux) is not blacklisted
< Server: Docker/1.10.3 (linux)
< Date: Fri, 19 Aug 2016 16:56:51 GMT
< Transfer-Encoding: chunked
```

**Comment by mmalina** [comment] 2016-08-22 11:17
Hmm, this is already the second issue that happens in CDK but not ADB, that is strange.
https://github.com/projectatomic/adb-atomic-developer-bundle/issues/513

**Comment by runcom** [comment] 2016-08-22 11:58
I'm looking at this just this afternoon (back from vacation today)

**Comment by runcom** [comment] 2016-08-22 13:57
@praveenkumar so this is happening only with the following routes:

```
/containers/json
/images/json
```

**Comment by praveenkumar** [comment] 2016-08-22 14:09
@runcom But these are the route that eclipse tooling use along with other endpoints, have we figure out why it's happening with these route only?

**Comment by runcom** [comment] 2016-08-22 14:14
> have we figure out why it's happening with these route only?

Haven't yet, I'm trying to to find out the difference in both commits used to build adb and cdk to understand more (but apparently, those commit hashes do not map to any commit in the git repo)

**Comment by runcom** [comment] 2016-08-22 14:15
@praveenkumar could you paste the output of docker version from cdk and adb?

**Comment by praveenkumar** [comment] 2016-08-22 14:17
> Could you paste the output of docker version from cdk and adb?

ADB: `Docker version 1.10.3, build d381c64-unsupported` based on CentOS-7
CDK: `Docker version 1.10.3, build 2a93377-unsupported` based on RHEL

**Comment by runcom** [comment] 2016-08-22 14:20
@praveenkumar on ADB could you paste the output of:

```
cat /proc/`pidof docker`/cmdline
```

**Comment by praveenkumar** [comment] 2016-08-22 14:28
> on ADB could you paste the output of:

```
$ ps aux | grep docker
root     14645  0.2  3.6 657576 36656 ?        Ssl  Aug12   7:17 /usr/bin/docker-current daemon --exec-opt native.cgroupdriver=systemd --selinux-enabled -H tcp://0.0.0.0:2376 -H unix:///var/run/docker.sock --tlscacert=/etc/docker/ca.pem --tlscert=/etc/docker/server-cert.pem --tlskey=/etc/docker/server-key.pem --tlsverify --storage-driver devicemapper --storage-opt dm.fs=xfs --storage-opt dm.thinpooldev=/dev/mapper/vg001-docker--pool --storage-opt dm.use_deferred_removal=true --storage-opt dm.use_deferred_deletion=true
vagrant  22671  0.0  0.0  10640   976 pts/0    R+   13:04   0:00 grep --color=auto docker
[vagrant@centos7-adb ~]$ cat /proc/14645/cmdline 
/usr/bin/docker-currentdaemon--exec-optnative.cgroupdriver=systemd--selinux-enabled-Htcp://0.0.0.0:2376-Hunix:///var/run/docker.sock--tlscacert=/etc/docker/ca.pem--tlscert=/etc/docker/server-cert.pem--tlskey=/etc/docker/server-key.pem--tlsverify--storage-driverdevicemapper--storage-optdm.fs=xfs--storage-optdm.thinpooldev=/dev/mapper/vg001-docker--pool--storage-optdm.use_deferred_removal=true--storage-optdm.use_deferred_deletion=true
```

**Comment by runcom** [comment] 2016-08-22 14:32
@praveenkumar so seems like you don't have any `--authorization-plugin` flag on ADB and it's working fine. Could you try to look at CDK, see if that flag is there, remove it, and re-test?

**Comment by praveenkumar** [comment] 2016-08-22 15:02
@runcom so I can see that for CDK below but why this is changing the behavior and what it do?

```
# cat /proc/12898/cmdline 
/usr/bin/docker-currentdaemon--authorization-plugin=rhel-push-plugin--exec-optnative.cgroupdriver=systemd--selinux-enabled-Htcp://0.0.0.0:2376-Hunix:///var/run/docker.sock--tlscacert=/etc/docker/ca.pem--tlscert=/etc/docker/server-cert.pem--tlskey=/etc/docker/server-key.pem--tlsverify--storage-driverdevicemapper--storage-optdm.fs=xfs--storage-optdm.thinpooldev=/dev/mapper/VolGroup00-docker--pool--storage-optdm.use_deferred_removal=true--storage-optdm.use_deferred_deletion=true--add-registryregistry.access.redhat.com
```

**Comment by brgnepal** [comment] 2016-08-22 15:05
@praveenkumar @runcom Also I found that CDK 2.1 does not have that `--authorization-plugin` which make it clear what is the root cause here.

```
[vagrant@rhel-cdk ~]$ sudo cat /proc/`pidof docker`/cmdline
BOOT_IMAGE=/vmlinuz-3.10.0-327.18.2.el7.x86_64 root=/dev/mapper/VolGroup00-root ro no_timer_check console=tty0 console=ttyS0,115200 net.ifnames=0 biosdevname=0 crashkernel=auto rd.lvm.lv=VolGroup00/root rhgb quiet LANG=en_US.UTF-8

[vagrant@rhel-cdk ~]$ sudo cat /etc/os-release 
NAME="Red Hat Enterprise Linux Server"
VERSION="7.2 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="7.2"
PRETTY_NAME="Red Hat Enterprise Linux Server 7.2 (Maipo)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.2:GA:server"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.2
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.2"
VARIANT="Container Development Kit (CDK)"
VARIANT_ID="cdk"
VARIANT_VERSION="2.1"
```

**Comment by runcom** [comment] 2016-08-22 15:08
Alright, it's definitely an issue with the docker plugin subsystem and probably something to be reported upstream as well. I'm going to investigate this more now and see if I can come up with a fix or workaround shortly.

**Comment by runcom** [comment] 2016-08-22 15:15
I can reproduce pretty easily on my laptop as well though (trying latest docker 1.12.1 to see if it's fixed there)

**Comment by runcom** [comment] 2016-08-22 15:36
Reported upstream https://github.com/docker/docker/issues/25927

**Comment by dustymabe** [comment] 2016-08-29 19:57
This is now fixed upstream

**Comment by runcom** [comment] 2016-08-29 21:55
And also in projectatomic/docker branch docker-1.12

**Comment by LalatenduMohanty** [comment] 2016-08-31 12:37
This is fixed in CDK2.2 RC2 builds. Can we close the bug now? cc @mmalina ?

**Closed as completed** 2016-09-01 12:22 UTC
Labels: blocker

**Comment by mmalina** [comment] 2016-09-02 17:00
@LalatenduMohanty yes, I can confirm that with cdk 2.2 rc3, Eclipse can connect to the docker daemon again.
