### ISSUE TITLE
VM won't start consistenly and abort startup with a timeout

### ISSUE THREAD

**Issue by hferentschik** [projectatomic/adb-atomic-developer-bundle#128] opened 2015-11-23 16:05 UTC
The configuration I am using can be found here - https://github.com/redhat-developer-tooling/openshift-vagrant

Running `vagrant up --no-provision` often results in the following outcome

```
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Removing hosts
==> default: No machine id, nothing removed from /etc/hosts
==> default: Importing base box 'cdk_v2'...
==> default: Matching MAC address for NAT networking...
==> default: Setting the name of the VM: openshift.cdk-2
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
    default: Adapter 2: hostonly
==> default: Forwarding ports...
    default: 22 => 2222 (adapter 1)
==> default: Checking for host entries
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
Timed out while waiting for the machine to boot. This means that
Vagrant was unable to communicate with the guest machine within
the configured ("config.vm.boot_timeout" value) time period.

If you look above, you should be able to see the error(s) that
Vagrant had when attempting to connect to the machine. These errors
are usually good hints as to what may be wrong.

If you're using a custom box, make sure that networking is properly
working and you're able to connect to the machine. It is a common
problem that networking isn't setup properly in these boxes.
Verify that authentication configurations are also setup properly,
as well.

If the box appears to be booting properly, you may want to increase
the timeout ("config.vm.boot_timeout") value.
```

According to @LalatenduMohanty this is an issue when using VirtualBox and private network.

**Comment by praveenkumar** [comment] 2015-11-23 16:22
```
==> default: Waiting for domain to get an IP address...
 INFO retryable: Retryable exception raised: #<Fog::Errors::TimeoutError: The specified wait_for timeout (2 seconds) was exceeded>
 INFO retryable: Retryable exception raised: #<Fog::Errors::TimeoutError: The specified wait_for timeout (2 seconds) was exceeded>
 INFO retryable: Retryable exception raised: #<Fog::Errors::TimeoutError: The specified wait_for timeout (2 seconds) was exceeded>
 INFO retryable: Retryable exception raised: #<Fog::Errors::TimeoutError: The specified wait_for timeout (2 seconds) was exceeded>
```

This is what I get when using libvirt provider and for me it's goes like forever and manually have to exit process sometime (not getting quite often).

**Comment by hferentschik** [comment] 2015-11-23 16:39
So it happens with libvirt as well - hmm

**Comment by bexelbie** [comment] 2015-11-24 11:46
When I get this error, I find that assigning a private IP or changing hte one assigned fixes it.  It seems like the network components are caching the old IP/MAC combo and not releasing it promptly on `vagrant destroy`  - this is at least my guest.  It isn't clear to me if this is vagrant or the network drivers.

**Comment by hferentschik** [comment] 2015-11-24 15:40
> When I get this error, I find that assigning a private IP or changing hte one assigned fixes it.

Interesting

>  It seems like the network components are caching the old IP/MAC combo and not releasing it promptly on vagrant destroy

It kind of would explain why waiting some time between 'vagrant up's seems to have better results. On the other hands, I had cases were I waited quite long and it still would not work.

Shouldn't there be somewhere on the net a reference to this then. Surely we are not the only one using private network IP.

**Comment by hferentschik** [comment] 2015-11-24 16:36
I might have found something - http://superuser.com/questions/854369/how-do-i-remove-a-virtualbox-host-only-network-adapter

I'll need to see whether I can re-produce the problem and if `VBoxManage` can then help.

**Comment by praveenkumar** [comment] 2015-11-25 06:24
Today I again reproduced this issue and after 5 attempts (back and forth 'vagrant up' - 'vagrant destroy'). http://stackoverflow.com/questions/22575261/vagrant-stuck-connection-timeout-retrying as per this answer I also attached GUI to it to find out if that is because some process need manual intervention but that was also not true.  
Overall as per my experience this issue occur randomly and I can't able to reproduce it successively (2-3 times) to check if removing network-adapter is  actually real solution. Once this issue occur just after next run I am not able to reproduce it (even not removing network-adapter). I think best we can do is put a note to documents. 
I am still open to tryout different workaround to make sure we have solid claim about this issue. Below is --debug flag logs when this issue occurred addition to what @hferentschik already put. 

```
If the box appears to be booting properly, you may want to increase
the timeout ("config.vm.boot_timeout") value.
ERROR vagrant: /usr/share/vagrant/lib/vagrant/action/builtin/wait_for_communicator.rb:62:in `call'
/usr/share/vagrant/lib/vagrant/action/warden.rb:34:in `call'
/usr/share/vagrant/plugins/providers/virtualbox/action/customize.rb:40:in `call'
/usr/share/vagrant/lib/vagrant/action/warden.rb:34:in `call'
/usr/share/vagrant/plugins/providers/virtualbox/action/boot.rb:18:in `call'
/usr/share/vagrant/lib/vagrant/action/warden.rb:34:in `call'
/usr/share/vagrant/plugins/providers/virtualbox/action/customize.rb:40:in `call'
/usr/share/vagrant/lib/vagrant/action/warden.rb:34:in `call'
/usr/share/vagrant/plugins/providers/virtualbox/action/sane_defaults.rb:38:in `call'
/usr/share/vagrant/lib/vagrant/action/warden.rb:34:in `call'
/usr/share/vagrant/lib/vagrant/action/builtin/set_hostname.rb:16:in `call'
/usr/share/vagrant/lib/vagrant/action/warden.rb:34:in `call'
/usr/share/vagrant/plugins/providers/virtualbox/action/forward_ports.rb:31:in `call'
/usr/share/vagrant/lib/vagrant/action/warden.rb:34:in `call'
/usr/share/vagrant/plugins/providers/virtualbox/action/network.rb:121:in `call'
/usr/share/vagrant/lib/vagrant/action/warden.rb:34:in `call'
/home/prkumar/.vagrant.d/gems/gems/landrush-0.18.0/lib/landrush/action/common.rb:24:in `handle_action_stack'
/home/prkumar/.vagrant.d/gems/gems/landrush-0.18.0/lib/landrush/action/setup.rb:7:in `call'
/usr/share/vagrant/lib/vagrant/action/warden.rb:34:in `call'
/usr/share/vagrant/plugins/providers/virtualbox/action/clear_network_interfaces.rb:26:in `call'
/usr/share/vagrant/lib/vagrant/action/warden.rb:34:in `call'
/usr/share/vagrant/plugins/providers/virtualbox/action/prepare_nfs_settings.rb:18:in `call'
/usr/share/vagrant/lib/vagrant/action/warden.rb:34:in `call'
/usr/share/vagrant/lib/vagrant/action/builtin/synced_folders.rb:86:in `call'
/usr/share/vagrant/lib/vagrant/action/warden.rb:34:in `call'
/usr/share/vagrant/lib/vagrant/action/builtin/synced_folder_cleanup.rb:28:in `call'
/usr/share/vagrant/lib/vagrant/action/warden.rb:34:in `call'
/usr/share/vagrant/plugins/synced_folders/nfs/action_cleanup.rb:25:in `call'
/usr/share/vagrant/lib/vagrant/action/warden.rb:34:in `call'
/usr/share/vagrant/plugins/providers/virtualbox/action/prepare_nfs_valid_ids.rb:12:in `call'
/usr/share/vagrant/lib/vagrant/action/warden.rb:34:in `call'
/usr/share/vagrant/lib/vagrant/action/builtin/handle_forwarded_port_collisions.rb:160:in `handle'
/usr/share/vagrant/lib/vagrant/action/builtin/handle_forwarded_port_collisions.rb:42:in `block in call'
/usr/share/vagrant/lib/vagrant/environment.rb:516:in `lock'
/usr/share/vagrant/lib/vagrant/action/builtin/handle_forwarded_port_collisions.rb:41:in `call'
/usr/share/vagrant/lib/vagrant/action/warden.rb:34:in `call'
/usr/share/vagrant/plugins/providers/virtualbox/action/prepare_forwarded_port_collision_params.rb:30:in `call'
/usr/share/vagrant/lib/vagrant/action/warden.rb:34:in `call'
/usr/share/vagrant/lib/vagrant/action/builtin/env_set.rb:19:in `call'
/usr/share/vagrant/lib/vagrant/action/warden.rb:34:in `call'
/usr/share/vagrant/lib/vagrant/action/builtin/provision.rb:80:in `call'
/usr/share/vagrant/lib/vagrant/action/warden.rb:34:in `call'
/usr/share/vagrant/plugins/providers/virtualbox/action/clear_forwarded_ports.rb:15:in `call'
/usr/share/vagrant/lib/vagrant/action/warden.rb:34:in `call'
/usr/share/vagrant/plugins/providers/virtualbox/action/set_name.rb:50:in `call'
/usr/share/vagrant/lib/vagrant/action/warden.rb:34:in `call'
/usr/share/vagrant/plugins/providers/virtualbox/action/clean_machine_folder.rb:17:in `call'
/usr/share/vagrant/lib/vagrant/action/warden.rb:34:in `call'
/usr/share/vagrant/plugins/providers/virtualbox/action/check_accessible.rb:18:in `call'
/usr/share/vagrant/lib/vagrant/action/warden.rb:34:in `call'
/usr/share/vagrant/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
/usr/share/vagrant/lib/vagrant/action/warden.rb:34:in `call'
/usr/share/vagrant/lib/vagrant/action/warden.rb:34:in `call'
/usr/share/vagrant/lib/vagrant/action/builder.rb:116:in `call'
/usr/share/vagrant/lib/vagrant/action/runner.rb:66:in `block in run'
/usr/share/vagrant/lib/vagrant/util/busy.rb:19:in `busy'
/usr/share/vagrant/lib/vagrant/action/runner.rb:66:in `run'
/usr/share/vagrant/lib/vagrant/action/builtin/call.rb:53:in `call'
/usr/share/vagrant/lib/vagrant/action/warden.rb:34:in `call'
/usr/share/vagrant/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
/usr/share/vagrant/lib/vagrant/action/warden.rb:34:in `call'
/usr/share/vagrant/lib/vagrant/action/warden.rb:34:in `call'
/usr/share/vagrant/lib/vagrant/action/builder.rb:116:in `call'
/usr/share/vagrant/lib/vagrant/action/runner.rb:66:in `block in run'
/usr/share/vagrant/lib/vagrant/util/busy.rb:19:in `busy'
/usr/share/vagrant/lib/vagrant/action/runner.rb:66:in `run'
/usr/share/vagrant/lib/vagrant/action/builtin/call.rb:53:in `call'
/usr/share/vagrant/lib/vagrant/action/warden.rb:34:in `call'
/usr/share/vagrant/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
/usr/share/vagrant/lib/vagrant/action/warden.rb:34:in `call'
/usr/share/vagrant/lib/vagrant/action/warden.rb:34:in `call'
/usr/share/vagrant/lib/vagrant/action/builder.rb:116:in `call'
/usr/share/vagrant/lib/vagrant/action/runner.rb:66:in `block in run'
/usr/share/vagrant/lib/vagrant/util/busy.rb:19:in `busy'
/usr/share/vagrant/lib/vagrant/action/runner.rb:66:in `run'
/usr/share/vagrant/lib/vagrant/action/builtin/call.rb:53:in `call'
/usr/share/vagrant/lib/vagrant/action/warden.rb:34:in `call'
/usr/share/vagrant/lib/vagrant/action/builtin/box_check_outdated.rb:36:in `call'
/usr/share/vagrant/lib/vagrant/action/warden.rb:34:in `call'
/usr/share/vagrant/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
/usr/share/vagrant/lib/vagrant/action/warden.rb:34:in `call'
/usr/share/vagrant/plugins/providers/virtualbox/action/check_virtualbox.rb:17:in `call'
/usr/share/vagrant/lib/vagrant/action/warden.rb:34:in `call'
/usr/share/vagrant/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
/usr/share/vagrant/lib/vagrant/action/warden.rb:34:in `call'
/usr/share/vagrant/lib/vagrant/action/warden.rb:34:in `call'
/usr/share/vagrant/plugins/providers/virtualbox/action/match_mac_address.rb:16:in `call'
/usr/share/vagrant/lib/vagrant/action/warden.rb:34:in `call'
/usr/share/vagrant/plugins/providers/virtualbox/action/import.rb:32:in `call'
/usr/share/vagrant/lib/vagrant/action/warden.rb:34:in `call'
/usr/share/vagrant/plugins/providers/virtualbox/action/customize.rb:40:in `call'
/usr/share/vagrant/lib/vagrant/action/warden.rb:34:in `call'
/usr/share/vagrant/plugins/providers/virtualbox/action/check_accessible.rb:18:in `call'
/usr/share/vagrant/lib/vagrant/action/warden.rb:34:in `call'
/usr/share/vagrant/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
/usr/share/vagrant/lib/vagrant/action/warden.rb:34:in `call'
/usr/share/vagrant/lib/vagrant/action/warden.rb:34:in `call'
/usr/share/vagrant/lib/vagrant/action/builder.rb:116:in `call'
/usr/share/vagrant/lib/vagrant/action/runner.rb:66:in `block in run'
/usr/share/vagrant/lib/vagrant/util/busy.rb:19:in `busy'
/usr/share/vagrant/lib/vagrant/action/runner.rb:66:in `run'
/usr/share/vagrant/lib/vagrant/action/builtin/call.rb:53:in `call'
/usr/share/vagrant/lib/vagrant/action/warden.rb:34:in `call'
/usr/share/vagrant/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
/usr/share/vagrant/lib/vagrant/action/warden.rb:34:in `call'
/usr/share/vagrant/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
/usr/share/vagrant/lib/vagrant/action/warden.rb:34:in `call'
/usr/share/vagrant/lib/vagrant/action/warden.rb:34:in `call'
/usr/share/vagrant/lib/vagrant/action/builtin/handle_box.rb:56:in `call'
/usr/share/vagrant/lib/vagrant/action/warden.rb:34:in `call'
/usr/share/vagrant/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
/usr/share/vagrant/lib/vagrant/action/warden.rb:34:in `call'
/usr/share/vagrant/lib/vagrant/action/warden.rb:34:in `call'
/usr/share/vagrant/lib/vagrant/action/builder.rb:116:in `call'
/usr/share/vagrant/lib/vagrant/action/runner.rb:66:in `block in run'
/usr/share/vagrant/lib/vagrant/util/busy.rb:19:in `busy'
/usr/share/vagrant/lib/vagrant/action/runner.rb:66:in `run'
/usr/share/vagrant/lib/vagrant/action/builtin/call.rb:53:in `call'
/usr/share/vagrant/lib/vagrant/action/warden.rb:34:in `call'
/usr/share/vagrant/plugins/providers/virtualbox/action/check_virtualbox.rb:17:in `call'
/usr/share/vagrant/lib/vagrant/action/warden.rb:34:in `call'
/usr/share/vagrant/lib/vagrant/action/builder.rb:116:in `call'
/usr/share/vagrant/lib/vagrant/action/runner.rb:66:in `block in run'
/usr/share/vagrant/lib/vagrant/util/busy.rb:19:in `busy'
/usr/share/vagrant/lib/vagrant/action/runner.rb:66:in `run'
/usr/share/vagrant/lib/vagrant/machine.rb:214:in `action_raw'
/usr/share/vagrant/lib/vagrant/machine.rb:191:in `block in action'
/usr/share/vagrant/lib/vagrant/environment.rb:516:in `lock'
/usr/share/vagrant/lib/vagrant/machine.rb:178:in `call'
/usr/share/vagrant/lib/vagrant/machine.rb:178:in `action'
/usr/share/vagrant/lib/vagrant/batch_action.rb:82:in `block (2 levels) in run'
```

**Comment by LalatenduMohanty** [comment] 2015-11-25 12:21
@praveenkumar @hferentschik I am still not able to consistently reproduce the issue.

**Comment by hferentschik** [comment] 2015-11-25 13:11
http://superuser.com/questions/854369/how-do-i-remove-a-virtualbox-host-only-network-adapter did also not help much. For sure I can see all the created network interfaces and some of them looked like they should have been cleaned up, but still using VBoxManage to remove vboxnet interfaces prior to 'vagrant up' did not seem to make a difference. 

Regarding reproducing, for me startup fails more often than not. I need around 4 attempts to get the VM up.

> I think best we can do is put a note to documents. 

Sure, we would for sure add some notes to the docs, but I would prefer to find the true cause. In particular I think we need to find out how it looks like on Windows.

**Comment by adietish** [comment] 2015-11-26 15:21
I ran into this yesterday but not today so far. Running Linux FC21 here, so it doesnt seem to be OSX related.

**Comment by LalatenduMohanty** [comment] 2015-12-01 12:12
I did some experiment with the `config.vm.network "private_network", ip: "#{PUBLIC_ADDRESS}"` . I tested with / without the config.vm.network with the default vagrantfile in Virtualbox i.e. vagrant box add adb <path to box> ; vagrant init adb . 

I think the issue is with config.vm.network "private_network"

**Comment by hferentschik** [comment] 2015-12-01 19:32
@LalatenduMohanty i think you are right, there is a connection to private network, but also to the ADB vm.

I tried the following minimal Vagrantfile:

```
Vagrant.configure(2) do |config|
  #config.vm.box = "cdk_v2"
  config.vm.box = "centos/7"
  config.vm.network "private_network", ip: "10.1.2.2"
end
```

Without private network both vms (cdk vs centos) start without problems. When I enable private network and also use the same IP we use otherwise, CDK won't start, CentOS does.

**Comment by LalatenduMohanty** [comment] 2015-12-03 12:33
I think the issue is with the resolv.conf of the guest CDK box. So as a work around I did following steps when I see the timeout issue and it worked for me

```
#Login in to the guest through Virtualbox i.e. Open Virtualbox -> Open the CDK VM-> login using username/password  : vagrant/vagrant 
#Restart the NetworkManager service
$ sudo systemctl restart NetworkManager
#Restart sshd
$ sudo systemctl restart sshd
```

CC @hferentschik

**Comment by maxandersen** [comment] 2015-12-03 12:43
since could require you to be quick here is a oneliner for it:

` vagrant ssh -c "sudo systemctl restart NetworkManager && sudo systemctl restart sshd"`

**Comment by praveenkumar** [comment] 2015-12-03 12:45
But this one liner works if vagrant is blocked at *ssh auth method* (have to try out)?

**Comment by maxandersen** [comment] 2015-12-07 08:00
For info I can only 1 out of maybe 5 times actually get a login screen going via virtualbox.
Most if not all times it just gives a black screen - no amount of typing makes it show up ;/

**Comment by LalatenduMohanty** [comment] 2015-12-07 12:36
Basically the issue is , sometime when we are using `config.vm.network "private_network", ip: "10.1.2.2"` the /etc/resolv.conf is not generated in the guest box. Which leads to this issue.

**Comment by hferentschik** [comment] 2015-12-07 12:47
So how do other VMs do it? How come it is only an issue for us?

Sent using CloudMagic [https://cloudmagic.com/k/d/mailapp?ct=pi&cv=6.0.64&pv=8.1.3]
On Mon, Dec 7, 2015 at 13:36, projectatomic/adb-atomic-developer-bundle
reply@reply.github.com
wrote:
Basically the issue is , sometime when we are using config.vm.network "private_network", ip: "10.1.2.2" the /etc/resolv.conf is generated in the guest box. Which leads to this issue.

—
Reply to this email directly or view it on GitHub
[https://github.com/projectatomic/adb-atomic-developer-bundle/issues/128#issuecomment-162512583] .[https://github.com/notifications/beacon/AASFojavcKNPmDJHjGI_n-IIJePANyf8ks5pNXTngaJpZM4GnorZ.gif]

**Comment by LalatenduMohanty** [comment] 2015-12-07 13:54
@hferentschik we definitly do something in the kickstart file which is causing this.  I think these issue is coming from the change we did to cache OSE docker image in the box. Trying to figure that out.

**Comment by LalatenduMohanty** [comment] 2015-12-07 13:56
Syslog also shows the same. NetworkManager going to failed state

``` r
Dec  7 07:31:55 localhost systemd-udevd: Network interface NamePolicy= disabled on kernel command line, ignoring.
Dec  7 07:31:57 localhost dhclient[694]: DHCPDISCOVER on eth1 to 255.255.255.255 port 67 interval 4 (xid=0x2e9278a7)
Dec  7 07:32:01 localhost dhclient[694]: DHCPDISCOVER on eth1 to 255.255.255.255 port 67 interval 7 (xid=0x2e9278a7)
Dec  7 07:32:08 localhost dhclient[694]: DHCPDISCOVER on eth1 to 255.255.255.255 port 67 interval 13 (xid=0x2e9278a7)
Dec  7 07:32:21 localhost dhclient[694]: DHCPDISCOVER on eth1 to 255.255.255.255 port 67 interval 15 (xid=0x2e9278a7)
Dec  7 07:32:23 localhost systemd: NetworkManager-wait-online.service: main process exited, code=exited, status=1/FAILURE
Dec  7 07:32:23 localhost systemd: Failed to start Network Manager Wait Online.
Dec  7 07:32:23 localhost systemd: Unit NetworkManager-wait-online.service entered failed state.
Dec  7 07:32:23 localhost systemd: NetworkManager-wait-online.service failed.
Dec  7 07:32:23 localhost systemd: Starting LSB: Bring up/down networking...
Dec  7 07:32:23 localhost network: Bringing up loopback interface:  Could not load file '/etc/sysconfig/network-scripts/ifcfg-lo'
Dec  7 07:32:23 localhost network: Could not load file '/etc/sysconfig/network-scripts/ifcfg-lo'
Dec  7 07:32:23 localhost network: Could not load file '/etc/sysconfig/network-scripts/ifcfg-lo'
Dec  7 07:32:23 localhost network: Could not load file '/etc/sysconfig/network-scripts/ifcfg-lo'
Dec  7 07:32:23 localhost network: [  OK  ]
Dec  7 07:32:24 localhost NetworkManager[653]: <warn>  (eth1): disconnecting connection 'eth0' for new activation request.
Dec  7 07:32:24 localhost NetworkManager[653]: <info>  (eth1): device state change: ip-config -> deactivating (reason 'new-activation') [70 110 60]
Dec  7 07:32:24 localhost NetworkManager[653]: <info>  NetworkManager state is now DISCONNECTING
Dec  7 07:32:24 localhost NetworkManager[653]: <info>  (eth1): disconnecting for new activation request.
Dec  7 07:32:24 localhost NetworkManager[653]: <info>  (eth1): device state change: deactivating -> disconnected (reason 'new-activation') [110 30 60]
Dec  7 07:32:24 localhost NetworkManager[653]: <info>  (eth1): canceled DHCP transaction, DHCP client pid 694
Dec  7 07:32:24 localhost NetworkManager[653]: <info>  (eth1): DHCPv4 state changed unknown -> done
Dec  7 07:32:24 localhost NetworkManager[653]: <info>  NetworkManager state is now DISCONNECTED
Dec  7 07:32:24 localhost NetworkManager[653]: <info>  (eth1): Activation: starting connection 'eth0' (5fb06bd0-0bb0-7ffb-45f1-d6edd65f3e03)
Dec  7 07:32:24 localhost dbus[635]: [system] Activating via systemd: service name='org.freedesktop.nm_dispatcher' unit='dbus-org.freedesktop.nm-dispatcher.service'
Dec  7 07:32:24 localhost systemd: Starting Network Manager Script Dispatcher Service...
Dec  7 07:32:24 localhost dbus-daemon: dbus[635]: [system] Activating via systemd: service name='org.freedesktop.nm_dispatcher' unit='dbus-org.freedesktop.nm-dispatcher.service'
Dec  7 07:32:24 localhost NetworkManager[653]: <info>  (eth1): device state change: disconnected -> prepare (reason 'none') [30 40 0]
Dec  7 07:32:24 localhost NetworkManager[653]: <info>  NetworkManager state is now CONNECTING
Dec  7 07:32:24 localhost NetworkManager[653]: <info>  (eth1): device state change: prepare -> config (reason 'none') [40 50 0]
Dec  7 07:32:24 localhost NetworkManager[653]: <info>  (eth1): device state change: config -> ip-config (reason 'none') [50 70 0]
Dec  7 07:32:24 localhost NetworkManager[653]: <info>  Activation (eth1) Beginning DHCPv4 transaction (timeout in 45 seconds)
Dec  7 07:32:24 localhost NetworkManager[653]: <info>  dhclient started with pid 908
Dec  7 07:32:24 localhost dbus[635]: [system] Successfully activated service 'org.freedesktop.nm_dispatcher'
Dec  7 07:32:24 localhost dbus-daemon: dbus[635]: [system] Successfully activated service 'org.freedesktop.nm_dispatcher'
Dec  7 07:32:24 localhost systemd: Started Network Manager Script Dispatcher Service.
Dec  7 07:32:24 localhost nm-dispatcher: Dispatching action 'down' for eth1
Dec  7 07:32:24 localhost dhclient[908]: DHCPDISCOVER on eth1 to 255.255.255.255 port 67 interval 7 (xid=0x31a39cd2)
Dec  7 07:32:31 localhost dhclient[908]: DHCPDISCOVER on eth1 to 255.255.255.255 port 67 interval 14 (xid=0x31a39cd2)
Dec  7 07:32:45 localhost dhclient[908]: DHCPDISCOVER on eth1 to 255.255.255.255 port 67 interval 16 (xid=0x31a39cd2)
Dec  7 07:33:01 localhost dhclient[908]: DHCPDISCOVER on eth1 to 255.255.255.255 port 67 interval 11 (xid=0x31a39cd2)
Dec  7 07:33:09 localhost NetworkManager[653]: <warn>  (eth1): DHCPv4 request timed out.
Dec  7 07:33:09 localhost NetworkManager[653]: <info>  (eth1): DHCPv4 state changed unknown -> timeout
Dec  7 07:33:09 localhost NetworkManager[653]: <info>  (eth1): canceled DHCP transaction, DHCP client pid 908
Dec  7 07:33:09 localhost NetworkManager[653]: <info>  (eth1): DHCPv4 state changed timeout -> done
Dec  7 07:33:09 localhost NetworkManager[653]: <info>  (eth1): device state change: ip-config -> failed (reason 'ip-config-unavailable') [70 120 5]
Dec  7 07:33:09 localhost NetworkManager[653]: <info>  NetworkManager state is now DISCONNECTED
Dec  7 07:33:09 localhost NetworkManager[653]: <info>  startup complete
Dec  7 07:33:09 localhost NetworkManager[653]: <warn>  (eth1): Activation: failed for connection 'eth0'
Dec  7 07:33:09 localhost NetworkManager[653]: <info>  (eth1): device state change: failed -> disconnected (reason 'none') [120 30 0]
Dec  7 07:33:09 localhost network: Bringing up interface eth0:  Error: Connection activation failed.
Dec  7 07:33:09 localhost NetworkManager[653]: <info>  Auto-activating connection 'eth0'.
Dec  7 07:33:09 localhost NetworkManager[653]: <info>  (eth1): Activation: starting connection 'eth0' (5fb06bd0-0bb0-7ffb-45f1-d6edd65f3e03)
```

**Comment by praveenkumar** [comment] 2015-12-07 14:04
@LalatenduMohanty Above syslog is from VM (Guest) or from host after failure?

**Comment by LalatenduMohanty** [comment] 2015-12-07 14:16
@praveenkumar yes, the log is from the guest

**Comment by LalatenduMohanty** [comment] 2015-12-08 08:23
I also noticed that network service also failed when we see this error

```
[vagrant@localhost ~]$ sudo systemctl status network
● network.service - LSB: Bring up/down networking
   Loaded: loaded (/etc/rc.d/init.d/network)
   Active: failed (Result: exit-code) since Tue 2015-12-08 03:17:25 EST; 3min 3s ago
     Docs: man:systemd-sysv-generator(8)
  Process: 10752 ExecStart=/etc/rc.d/init.d/network start (code=exited, status=1/FAILURE)

Dec 08 03:17:25 localhost.localdomain network[10752]: RTNETLINK answers: File exists
Dec 08 03:17:25 localhost.localdomain network[10752]: RTNETLINK answers: File exists
Dec 08 03:17:25 localhost.localdomain network[10752]: RTNETLINK answers: File exists
Dec 08 03:17:25 localhost.localdomain network[10752]: RTNETLINK answers: File exists
Dec 08 03:17:25 localhost.localdomain network[10752]: RTNETLINK answers: File exists
Dec 08 03:17:25 localhost.localdomain network[10752]: RTNETLINK answers: File exists
Dec 08 03:17:25 localhost.localdomain systemd[1]: network.service: control process exited, code=exited status=1
Dec 08 03:17:25 localhost.localdomain systemd[1]: Failed to start LSB: Bring up/down networking.
Dec 08 03:17:25 localhost.localdomain systemd[1]: Unit network.service entered failed state.
Dec 08 03:17:25 localhost.localdomain systemd[1]: network.service failed.
```

Found this https://access.redhat.com/solutions/1549693?tour=6 , as per the fix adding following to ks file and doing a scratch build

```
echo "NM_CONTROLLED=no" | tee --append  /etc/sysconfig/network-scripts/ifcfg-lo > /dev/null
systemctl restart network
```

**Comment by hferentschik** [comment] 2015-12-09 09:44
When will this scratch build be available? Getting into a state where I can start the VM consistently would save me heaps of time? Have you started with weekly deliverables?

**Comment by praveenkumar** [comment] 2015-12-09 10:31
@hferentschik Builds which lala did still consist of this issue. I tried it out so we still have to debug more.

> Have you started with weekly deliverables?

It's in our internal server right now.

**Comment by LalatenduMohanty** [comment] 2015-12-09 11:34
@hferentschik Weekly builds -> yes, but as @praveenkumar mentioned , this issue is not fixed yet.
So I am more and more convinced that this is a networking issue around how dhcp for the vagrantbox supposed to work

**Comment by hferentschik** [comment] 2015-12-09 12:37
> It's in our internal server right now.

Cool, I grab the latest asap

> Weekly builds -> yes, but as @praveenkumar mentioned , this issue is not fixed yet.

:-(

**Comment by praveenkumar** [comment] 2015-12-10 07:06
I hope finally we are able to fix this issue, I used fedora kickstart file bits for network section after 20 times run/destroy didn't observe it. Builds artifacts are available to our internal server right now (10-Dec-2015 directory).

@hferentschik  @maxandersen  Please give it a try and let me know if you still face it.

**Comment by hferentschik** [comment] 2015-12-10 09:28
Awesome, I'll give it a try. I am on the train this morning. I'll need to wait
for a better connection later today to get the box file. If it works, I would be
interested to know where the issue lies or which diff makes the difference.

Sent using CloudMagic [https://cloudmagic.com/k/d/mailapp?ct=pi&cv=6.0.64&pv=8.1.3]
On Thu, Dec 10, 2015 at 08:06, projectatomic/adb-atomic-developer-bundle
reply@reply.github.com
wrote:
I hope finally we are able to fix this issue, I used fedora kickstart file bits
for network section after 20 times run/destroy didn't observe it. Builds
artifacts are available to our internal server right now (10-Dec-2015
directory).

@hferentschik [https://github.com/hferentschik] @maxandersen [https://github.com/maxandersen] Please give it a try and let me know if you still face it.

—
Reply to this email directly or view it on GitHub
[https://github.com/projectatomic/adb-atomic-developer-bundle/issues/128#issuecomment-163519840] .[https://github.com/notifications/beacon/AASFovsTCJhkAVT40rJcQhTG3dslTllRks5pORvmgaJpZM4GnorZ.gif]

**Comment by hferentschik** [comment] 2015-12-11 15:13
I confirmed that the latest builds fix the problem, on OS X as well as on Windows 10 :-)

**Comment by hferentschik** [comment] 2015-12-11 15:14
Please merge PR asap.

**Comment by mmalina** [comment] 2015-12-14 10:42
hi all,
I'm still seeing one timeout:

```
    default: Warning: Connection timeout. Retrying...
    default: Warning: Remote connection disconnect. Retrying...
==> default: Machine booted and ready!
```

This is something that I've seen before with the CDK 2 downloaded from CSP. After one time out, it works. This is happening consistently for me at every vagrant up. Is this something that can be fixed as well? Shall I create a new issue for this?

**Comment by LalatenduMohanty** [comment] 2015-12-14 10:56
@mmalina Have you tried the latest CDK weekly builds? in ADB the PR to fix this has not merged yet.

**Comment by mmalina** [comment] 2015-12-14 11:22
I created a new issue here: #147

**Closed as completed** 2015-12-14 17:07 UTC
Labels: bug, blocker, focus:devex
