### ISSUE TITLE
Unexpected package change in build of ADB

### ISSUE THREAD

**Issue by bexelbie** [projectatomic/adb-atomic-developer-bundle#398] opened 2016-05-20 14:18 UTC
ADB 2.1 recently shipped.  It contains these docker packages:

```
Installed Packages
docker.x86_64                                     1.9.1-25.el7.centos                    @koji-override-0
docker-forward-journald.x86_64                    1.9.1-25.el7.centos                    @koji-override-0
docker-selinux.x86_64                             1.9.1-25.el7.centos                    @extras         
```

A build of ADB that I submitted today contains these packages:

```
Installed Packages
docker.x86_64                                      1.9.1-40.el7.centos                   @koji-override-0
docker-common.x86_64                               1.9.1-40.el7.centos                   @koji-override-0
docker-forward-journald.x86_64                     1.9.1-40.el7.centos                   @koji-override-0
docker-selinux.x86_64                              1.9.1-40.el7.centos                   @extras         
```

How can I get a build that has what was in ADB 2.1?

@LalatenduMohanty any advice?

**Comment by LalatenduMohanty** [comment] 2016-05-20 16:55
@bexelbie With the existing build scripts you can not get the exact old RPMs through a build if the CentOS base OS has new packages now.  Because we use CentOS's RPM tree. If the tree has updated RPMs the Vagrantbox will get new RPMs. If you want to get exact RPMs then you have to use `yum downgrade` command to do it either in the kickstartfile or in a Vagrantfile.

**Comment by bexelbie** [comment] 2016-05-24 10:46
Should we have reproducible builds as part of this project?

**Comment by praveenkumar** [comment] 2016-05-25 11:24
> Should we have reproducible builds as part of this project?

If we want reproducible builds then we always have to tag version to different packages like docker=1.9.1-25 which I don't think feasible because in case of purge, for older version of packages it might fail.

**Comment by LalatenduMohanty** [comment] 2016-06-09 18:37
Closing this as I believe this is resolved.

**Closed as completed by LalatenduMohanty** 2016-06-09 18:37 UTC
