### ISSUE TITLE
Add suspend_mode = "managedsave" to libvirt configuration

### ISSUE THREAD

**Issue by rimolive** [projectatomic/adb-atomic-developer-bundle#447] opened 2016-06-16 16:12 UTC
Please give us a chance to save development time and a way to free up resources by adding:

```
v.suspend_mode = "managedsave"
```

To Vagrantfile. That way every `vagrant suspend` will save Virtual Machine state and we don't need to do rework to configure development environment every time we need to spin up the VM again.

**Comment by LalatenduMohanty** [comment] 2016-06-21 05:40
@rimolive Have you used `vagrant halt` ? It seems `vagrant halt` will be suitable for your use case. Can you please let us know more about your use case.

**Comment by LalatenduMohanty** [comment] 2016-06-21 05:44
I think the difference between `vagrant suspand` and `vagrant halt` is that an user want to reuse his exact setup without running provisioning scripts again which is expected in `vagrant halt` workflow i.e. vagrant up -> vagrant halt -> vagrant up.

And the `vagrant suspand` workflow is `vagrant suspand` -> `vagrant resume`. 

I have not used vagrant suspand and resume so need to test it.

**Comment by rimolive** [comment] 2016-06-21 13:21
@LalatenduMohanty, I tested it. Also, I used `vagrant halt` many times and lost the work I did.

With managedsave at least I can tell libvirt to suspend + save the VM state so I can recover with `vagrant resume` later

What I proposed (and submitted the PR) I already tested and it works great. Unless you think this is not a good improvement (or not an improvement at all) you can make sure that this works.

**Comment by LalatenduMohanty** [comment] 2016-06-21 15:42
@rimolive Thanks for the PR. I can see  vagrant suspand -> vagrant resume work flow would be useful for some for sure.

**Comment by praveenkumar** [comment] 2016-06-22 06:28
@rimolive We also have to test it with Virtualbox provider or you tested that also?

**Comment by LalatenduMohanty** [comment] 2016-06-22 11:17
@rimolive I tested `vagrant suspand -> vagrant resume` and it worked fine for me. I did not loose my work. Can you please give us steps to reproduce?

Also it seems  [vagrant-libvirt](https://github.com/vagrant-libvirt/vagrant-libvirt) plugin take care of managedsave in `vagrant suspand`

**Comment by praveenkumar** [comment] 2016-07-07 09:01
@rimolive @LalatenduMohanty Do we have anything else here to discuss because there is a PR which attach to this discussion and till now from this discussion I don't think we need that PR.

**Comment by rimolive** [comment] 2016-07-10 17:09
@LalatenduMohanty, you are correct. But what happen with `vagrant suspend` command is that the host resources will still be available for the VM and that means it will consume unnecessary Memory. My proposal is to have `vagrant suspend` save the VM state and halt the VM to save resources by just adding the option I added in the PR.

@praveenkumar, take a look at my comment and see if it's reasonable to have it added in the code.

**Comment by praveenkumar** [comment] 2016-07-11 06:31
@rimolive I looked into `managedsave` and looks like it is only option for libvirt provider because this is domain specific option and I am afraid it will not going to  work with Virtualbox provider https://github.com/vagrant-libvirt/vagrant-libvirt/blob/7955d437302fdcf18889763259a0c9e54366d88b/README.md#domain-specific-options , I don't have issue with PR but then it will change behavior between providers.

**Comment by rimolive** [comment] 2016-07-11 13:37
@praveenkumar, so let's do that way: I'll do some research about the `vagrant suspend` behavior in Virtualbox environments, and if there's something to change I'll add in my PR. What do you think?

**Comment by praveenkumar** [comment] 2016-07-12 11:30
> What do you think?

@rimolive Sounds good.

**Comment by praveenkumar** [comment] 2016-08-04 05:06
ping @rimolive , Any outcome from your research?

**Comment by rimolive** [comment] 2016-08-04 13:06
@praveenkumar I'll have a test result until the end of the day

**Comment by rimolive** [comment] 2016-08-05 10:10
@praveenkumar from my tests with virtualbox the default behavior is already save VM state, so what my PR does is make libvirt behave the same way as virtualbox.

**Comment by praveenkumar** [comment] 2016-08-12 04:56
@rimolive Thanks for testing we will do bit of testing ourself and then add this change.

**Comment by praveenkumar** [comment] 2016-08-26 04:08
> Also it seems vagrant-libvirt plugin take care of managedsave in vagrant suspend

@LalatenduMohanty as per vagrant-libvirt readme looks like managedsave is only called when it explicitly defined in the Vagrantfile as config option. 

https://github.com/vagrant-libvirt/vagrant-libvirt/blob/master/lib/vagrant-libvirt/action/suspend_domain.rb#L21

```
suspend_mode - What is done on vagrant suspend. Possible values: 'pause', 
'managedsave'. Pause mode executes a la virsh suspend, which just pauses execution of a VM, not freeing resources. Managed save mode does a la virsh managedsave which frees resources suspending a domain.
```

Since PR only have that option set for libvirt and not affecting any provider so I am in favor of it until we have any other valid reason.

**Comment by LalatenduMohanty** [comment] 2016-08-26 06:37
@praveenkumar @rimolive sounds good to me. Will merge the PR.

**Comment by LalatenduMohanty** [comment] 2016-08-26 06:38
Closing the issue as the PR is merged.

**Closed as completed by LalatenduMohanty** 2016-08-26 06:38 UTC
Labels: enhancement
