### ISSUE TITLE
building JBoss Tomcat fails

### ISSUE THREAD

**Issue by goern** [projectatomic/adb-atomic-developer-bundle#153] opened 2015-12-15 12:07 UTC
Using a new project and building the jboss-tomcat project in there leads to a failure:

```
I1215 12:02:58.614585       1 sti.go:213] Using provided push secret for pushing 172.30.149.253:5000/test2/tomcat:latest image
I1215 12:02:58.616358       1 sti.go:217] Pushing 172.30.149.253:5000/test2/tomcat:latest image ...
E1215 12:02:58.639196       1 dockerutil.go:74] push for image 172.30.149.253:5000/test2/tomcat:latest failed, will retry in 5s seconds ...
E1215 12:03:03.641546       1 dockerutil.go:74] push for image 172.30.149.253:5000/test2/tomcat:latest failed, will retry in 5s seconds ...
E1215 12:03:08.643828       1 dockerutil.go:74] push for image 172.30.149.253:5000/test2/tomcat:latest failed, will retry in 5s seconds ...
E1215 12:03:13.646157       1 dockerutil.go:74] push for image 172.30.149.253:5000/test2/tomcat:latest failed, will retry in 5s seconds ...
E1215 12:03:18.648541       1 dockerutil.go:74] push for image 172.30.149.253:5000/test2/tomcat:latest failed, will retry in 5s seconds ...
E1215 12:03:23.650895       1 dockerutil.go:74] push for image 172.30.149.253:5000/test2/tomcat:latest failed, will retry in 5s seconds ...
E1215 12:03:28.653559       1 dockerutil.go:74] push for image 172.30.149.253:5000/test2/tomcat:latest failed, will retry in 5s seconds ...
I1215 12:03:33.655532       1 sti.go:222] Registry server Address: 
I1215 12:03:33.655557       1 sti.go:223] Registry server User Name: serviceaccount
I1215 12:03:33.655562       1 sti.go:224] Registry server Email: serviceaccount@example.org
I1215 12:03:33.655566       1 sti.go:229] Registry server Password: <<non-empty>>
F1215 12:03:33.655576       1 builder.go:59] Build error: Failed to push image. Response from registry is: unable to ping registry endpoint https://172.30.149.253:5000/v0/
v2 ping attempt failed with error: Get https://172.30.149.253:5000/v2/: tls: oversized record received with length 20527
v1 ping attempt failed with error: Get https://172.30.149.253:5000/v1/_ping: tls: oversized record received with length 20527
```

**Comment by LalatenduMohanty** [comment] 2015-12-15 12:55
@goern Which ADB version you have used?

**Comment by praveenkumar** [comment] 2015-12-15 15:27
@goern can you do vagrant ssh and see if you have below containers are running I think you dont have registry container by default. I have to open a bug because of SELinux issue.

```
$ docker ps
CONTAINER ID        IMAGE                                   COMMAND                  CREATED             STATUS              PORTS               NAMES
b7cbc3c91c04        openshift/origin-haproxy-router:v1.1    "/usr/bin/openshift-r"   3 minutes ago       Up 3 minutes                            k8s_router.4c5cee9_router-1-2pfc6_default_8cea5e69-a33c-11e5-9898-5254000c59d3_2ecd34cc
5a941d15d6e6        openshift/origin-docker-registry:v1.1   "/bin/sh -c 'REGISTRY"   3 minutes ago       Up 3 minutes                            k8s_registry.451b18cc_docker-registry-1-1xaoc_default_86576516-a33c-11e5-9898-5254000c59d3_0bb42a01
a2c7011952f3        openshift/origin-pod:v1.1               "/pod"                   3 minutes ago       Up 3 minutes                            k8s_POD.4d0ddc3f_router-1-2pfc6_default_8cea5e69-a33c-11e5-9898-5254000c59d3_ef449aa6
8d2e8c8db7ab        openshift/origin-pod:v1.1               "/pod"                   3 minutes ago       Up 3 minutes                            k8s_POD.cc3ffd58_docker-registry-1-1xaoc_default_86576516-a33c-11e5-9898-5254000c59d3_d8df2963
2f53766b7585        openshift/origin                        "/usr/bin/openshift s"   5 minutes ago       Up 5 minutes                            origin
```

**Comment by LalatenduMohanty** [comment] 2015-12-16 07:01
@goern @praveenkumar I still dont know the steps to reproduce the issue. Can you please put that in the issue?

**Comment by praveenkumar** [comment] 2015-12-17 06:11
This issue is still exist but it not with the vagrant box but I think it's more like origin docker image, will ask hardy to look into it.

```
mongodb@2.0.52 node_modules/mongodb
├── es6-promise@2.1.1
├── readable-stream@1.0.31 (isarray@0.0.1, inherits@2.0.1, string_decoder@0.10.31, core-util-is@1.0.2)
├── kerberos@0.0.17 (nan@2.0.9)
└── mongodb-core@1.2.28 (bson@0.4.20)
E1217 06:06:41.843440       1 util.go:85] npm info ok 
I1217 06:06:58.394799       1 sti.go:213] Using provided push secret for pushing 172.30.130.75:5000/test/nodejs-example:latest image
I1217 06:06:58.394825       1 sti.go:217] Pushing 172.30.130.75:5000/test/nodejs-example:latest image ...
E1217 06:06:58.400654       1 dockerutil.go:74] push for image 172.30.130.75:5000/test/nodejs-example:latest failed, will retry in 5s seconds ...
E1217 06:07:03.412667       1 dockerutil.go:74] push for image 172.30.130.75:5000/test/nodejs-example:latest failed, will retry in 5s seconds ...
E1217 06:07:08.415582       1 dockerutil.go:74] push for image 172.30.130.75:5000/test/nodejs-example:latest failed, will retry in 5s seconds ...
E1217 06:07:13.431312       1 dockerutil.go:74] push for image 172.30.130.75:5000/test/nodejs-example:latest failed, will retry in 5s seconds ...
E1217 06:07:18.434756       1 dockerutil.go:74] push for image 172.30.130.75:5000/test/nodejs-example:latest failed, will retry in 5s seconds ...
E1217 06:07:23.437313       1 dockerutil.go:74] push for image 172.30.130.75:5000/test/nodejs-example:latest failed, will retry in 5s seconds ...
E1217 06:07:28.441089       1 dockerutil.go:74] push for image 172.30.130.75:5000/test/nodejs-example:latest failed, will retry in 5s seconds ...
I1217 06:07:33.448060       1 sti.go:222] Registry server Address: 
I1217 06:07:33.448085       1 sti.go:223] Registry server User Name: serviceaccount
I1217 06:07:33.448093       1 sti.go:224] Registry server Email: serviceaccount@example.org
I1217 06:07:33.448101       1 sti.go:229] Registry server Password: <<non-empty>>
F1217 06:07:33.448116       1 builder.go:59] Build error: Failed to push image. Response from registry is: unable to ping registry endpoint https://172.30.130.75:5000/v0/
v2 ping attempt failed with error: Get https://172.30.130.75:5000/v2/: tls: oversized record received with length 20527
v1 ping attempt failed with error: Get https://172.30.130.75:5000/v1/_ping: tls: oversized record received with length 20527
```

**Comment by praveenkumar** [comment] 2015-12-18 05:13
https://github.com/openshift/origin/issues/6362 same issue which we are facing for adb box.

**Comment by praveenkumar** [comment] 2016-01-27 05:50
With latest release of ADB-1.6 and updated openshift vagrant file this issue is no longer exist.

@goern  Can you please confirm once, will close this issue after your confirmation.

**Comment by bexelbie** [comment] 2016-02-21 13:53
@goern please confirm this against 1.7 (or latest)

**Comment by praveenkumar** [comment] 2016-03-14 05:47
@goern Issue which you were facing before is solved and it would be good if you try it on latest version of ADB.

PS. I am closing this issue, if you again hit this issue then we reopen it.

**Closed as completed by praveenkumar** 2016-03-14 05:47 UTC
Labels: bug
