### ISSUE TITLE
kubernetes services - network

### ISSUE THREAD

**Issue by kadel** [projectatomic/adb-atomic-developer-bundle#108] opened 2015-10-29 12:58 UTC
Hi,
I am having strange issues with kubernetes services inside adb.
I cannot connect to any of services a I create, and not event to default kubernetes apiserver service 

```
# curl -k https://10.254.0.1:443
curl: (7) Failed connect to 10.254.0.1:443; Connection timed out 
```

in tcpdump I can see that request is send but there is no response 

```
08:53:42.197406 IP 192.168.121.116.45530 > 10.254.0.1.https: Flags [S], seq 1137755276, win 14600, options [mss 1460,sackOK,TS val 6728096 ecr 0,nop,wscale 7], length 0
```

**Comment by dharmit** [comment] 2016-01-08 07:40
@kadel 

I am not able to reproduce this. Can you provide more info? I started a fresh ADB box yesterday and it seems to be working. Also I tried a few examples in **nulecule-library** repo and the services created from those examples worked fine.

What's the status of the k8s services on the node?

```
  kube-apiserver.service                                                                   loaded active running   Kubernetes API Server
  kube-controller-manager.service                                                          loaded active running   Kubernetes Controller Manager
  kube-proxy.service                                                                       loaded active running   Kubernetes Kube-Proxy Server
  kube-scheduler.service                                                                   loaded active running   Kubernetes Scheduler Plugin
  kubelet.service                                                                          loaded active running   Kubernetes Kubelet Server
  etcd.service                                                                             loaded active running   Etcd Server

```

**Comment by LalatenduMohanty** [comment] 2016-01-08 07:54
@dharmit thats a good news. Can you also list which are the examples you have tried?

**Comment by dharmit** [comment] 2016-01-08 08:25
@LalatenduMohanty sure. I will create an issue and update it.

**Comment by kadel** [comment] 2016-01-11 11:34
hey, 
I can confirm that now everything works fine using current box `projectatomic/adb` version 1.5.0
and this [Vagrantfile](https://github.com/projectatomic/adb-atomic-developer-bundle/blob/master/components/centos/centos-k8s-singlenode-setup/Vagrantfile)

**Comment by praveenkumar** [comment] 2016-01-12 07:22
Thanks @kadel , Closing this issue.

**Closed as completed by praveenkumar** 2016-01-12 07:22 UTC
Labels: bug, blocker
