### ISSUE TITLE
Vagrant up fails on Mac

### ISSUE THREAD

**Issue by naina-verma** [projectatomic/adb-atomic-developer-bundle#521] opened 2016-08-23 09:20 UTC
Vagrant up fails on Mac
Environment : Mac with virtualbox provider
Steps to reproduce 
After taking long time for vagrant up it fails with the error message 
Detailed logs - https://gist.github.com/naina-verma/f65b64655b2903530f373f7124da4618

```
`default: Warning: Authentication failure. Retrying...
Timed out while waiting for the machine to boot. This means that
Vagrant was unable to communicate with the guest machine within
the configured ("config.vm.boot_timeout" value) time period.

If you look above, you should be able to see the error(s) that
Vagrant had when attempting to connect to the machine. These errors
are usually good hints as to what may be wrong.

If you're using a custom box, make sure that networking is properly
working and you're able to connect to the machine. It is a common
problem that networking isn't setup properly in these boxes.
Verify that authentication configurations are also setup properly,
as well.

If the box appears to be booting properly, you may want to increase
the timeout ("config.vm.boot_timeout") value.`
```

**Comment by brgnepal** [comment] 2016-08-23 09:26
@naina-verma Could you add further details like versions of Vagrant, Virtualbox etc?

**Comment by naina-verma** [comment] 2016-08-23 09:31
Installed Version: 1.8.5
can find virtualbox version this machine is remote

**Comment by optak** [comment] 2016-08-23 09:36
VirtualBox is in version 5.1.4r110228
If there is anything that GUI access is needed, I can do it.

**Comment by brgnepal** [comment] 2016-08-23 09:36
Vagrant 1.8.5 seems to be broken with authentication issue which you have experienced.

Upstream issue - https://github.com/mitchellh/vagrant/issues/7610.
Please verify and take the action accordingly.

**Comment by LalatenduMohanty** [comment] 2016-08-23 10:19
Closing the issue as the issue is getting tracked at https://github.com/mitchellh/vagrant/issues/7610

**Closed as completed by LalatenduMohanty** 2016-08-23 10:19 UTC
