### ISSUE TITLE
Rebuild ADB when new atomic CLI ships

### ISSUE THREAD

**Issue by bexelbie** [projectatomic/adb-atomic-developer-bundle#397] opened 2016-05-20 13:07 UTC
See: https://github.com/projectatomic/atomic/issues/339

This bug causes all atomic apps to fail as documented.

**Comment by LalatenduMohanty** [comment] 2016-05-25 07:31
@bexelbie this is duplicate of https://github.com/projectatomic/adb-atomic-developer-bundle/issues/329
We should close one of them. Feel free to close one you like.

**Closed as completed** 2016-05-25 09:01 UTC
